[package]
name = "wow-tentacli-adapter"
version = "0.1.0"
edition.workspace = true
publish.workspace = true

[dependencies]
tentacli.workspace = true
wow-domain.workspace = true
wow-state.workspace = true
tokio.workspace = true
anyhow.workspace = true
tracing.workspace = true

[lints]
workspace = true
